CUDA_VISIBLE_DEVICES=0 llamafactory-cli train \
    --stage dpo \
    --do_train True \
    --model_name_or_path "************************************/reasoner-guide-r1" \
    --preprocessing_num_workers 16 \
    --finetuning_type lora \
    --dataset Claim-reason-4o-guide-merge-nei-r2 \
    --dataset_dir ./ \
    --template llama3 \
    --flash_attn auto \
    --cutoff_len 4000 \
    --learning_rate 5e-6 \
    --num_train_epochs 3.0 \
    --max_samples 100000 \
    --per_device_train_batch_size 6 \
    --gradient_accumulation_steps 16 \
    --lr_scheduler_type cosine \
    --output_dir "./saves/LLaMA3-8B-64/claim-reason-guide-nei-r2" \
    --overwrite_cache \
    --overwrite_output_dir \
    --logging_steps 50 \
    --lora_rank 64 \
    --warmup_steps 0 \
    --save_steps 50 \
    --eval_steps 50 \
    --plot_loss True \
    --evaluation_strategy steps \
    --load_best_model_at_end \
    --val_size 0.1 \
    --fp16